// Anime OST quiz seed data
export const ANIME_SONGS = [
    ['Gurenge LiSA Demon Slayer OP MV', 'LiSA - 홍련화 (귀멸의 칼날)'],
    ['LiSA Homura Demon Slayer movie MV', 'LiSA - 불꽃 (귀멸의 칼날: 무한열차)'],
    ['LiSA Zankyosanka Demon Slayer MV', 'LiSA - 잔향산가 (귀멸의 칼날: 유곽편)'],
    ['YOASOBI Idol Oshi no Ko MV', '요아소비 - 아이돌 (최애의 아이)'],
    ['Official HIGE DANdism Mixed Nuts Spy Family', '히게단 - Mixed Nuts (스파이 패밀리)'],
    ['RADWIMPS Sparkle Your Name MV', 'RADWIMPS - 스파클 (너의 이름은.)'],
    ['RADWIMPS Zenzenzense Your Name MV', 'RADWIMPS - 전전전세 (너의 이름은.)'],
    ['RADWIMPS Nandemonaiya Your Name', 'RADWIMPS - 아무것도 아니야 (너의 이름은.)'],
    ['unravel TK Ling Tosite Sigure Tokyo Ghoul OP', 'TK - unravel (도쿄 구울)'],
    ['SiM The Rumbling Attack on Titan', 'SiM - The Rumbling (진격의 거인)'],
    ['Linked Horizon Shinzou wo Sasageyo AOT', 'Linked Horizon - 심장을 바쳐라 (진격의 거인)'],
    ['Linked Horizon Guren no Yumiya AOT', 'Linked Horizon - 홍련의 화살 (진격의 거인)'],
    ['FLOW GO Naruto OP MV', 'FLOW - GO!!! (나루토)'],
    ['Blue Bird Ikimonogakari Naruto MV', '이키모노가카리 - 블루버드 (나루토)'],
    ['Silhouette KANA BOON Naruto MV', 'KANA-BOON - Silhouette (나루토)'],
    ['Haruka Kanata AKFG Naruto MV', 'AKFG - 하루카 카나타 (나루토)'],
    ['Wind Akeboshi Naruto ED MV', 'Akeboshi - Wind (나루토)'],
    ['Eve Kaikai Kitan Jujutsu Kaisen OP', 'Eve - 廻廻奇譚 (주술회전)'],
    ['10-FEET Dai Zero Kan Slam Dunk', '10-FEET - 제0감 (슬램덩크)'],
    ['Ado New Genesis One Piece Film Red', 'Ado - 신시대 (원피스 필름 레드)'],
    ['Ado Tot Musica One Piece MV', 'Ado - Tot Musica (원피스 필름 레드)'],
    ['We Are One Piece OP1 MV', 'Kitadani Hiroshi - We Are! (원피스)'],
    ['Creepy Nuts Bling Bang Bang Born Mashle', 'Creepy Nuts - Bling-Bang-Bang-Born (마슐)'],
    ['Creepy Nuts Otonoke Dandadan', 'Creepy Nuts - 오토노케 (단다단)'],
    ['Mrs GREEN APPLE Inferno Fire Force', 'Mrs. GREEN APPLE - 인페르노 (불꽃소방대)'],
    ['BUMP OF CHICKEN SOUVENIR Spy Family', 'BUMP OF CHICKEN - SOUVENIR (스파이 패밀리)'],
    ['Aimer Zankyou Sanka Demon Slayer', 'Aimer - 잔향산가 (귀멸의 칼날)'],
    ['Kenshi Yonezu KICK BACK Chainsaw Man', '요네즈 켄시 - KICK BACK (체인소 맨)'],
    ['King Gnu SPECIALZ Jujutsu Kaisen S2', 'King Gnu - SPECIALZ (주술회전 2기)'],
    ['SPYAIR Imagination Haikyuu OP', 'SPYAIR - 이매지네이션 (하이큐)'],
    ['BURNOUT SYNDROMES Hikari Are Haikyuu', 'BURNOUT SYNDROMES - Hikari Are (하이큐)'],
    ['Tatsuya Kitani Seija no Koushin Chainsaw Man', '키타니 타츠야 - 성자의 행진 (체인소 맨)'],
    ['YOASOBI The Blessing Gundam Suisei', '요아소비 - 축복 (건담: 수성의 마녀)'],
    ['YOASOBI Yuusha Frieren MV', '요아소비 - 용자 (장송의 프리렌)'],
    ['Miwa Brave Song Angel Beats', 'Lia - My Soul Your Beats (엔젤비츠)'],
    ['Again YUI Fullmetal Alchemist OP', 'YUI - again (강철의 연금술사)'],
    ['Rewrite Asian Kung-Fu Generation FMA', 'AKFG - Rewrite (강철의 연금술사)'],
    ['Period Chemistry Fullmetal Alchemist', 'CHEMISTRY - Period (강철의 연금술사)'],
    ['Hikaru Nara Goose House Your Lie in April', 'Goose house - 빛나는 너에게 (4월은 너의 거짓말)'],
    ['Orange 7!! Your Lie in April ED', '7!! - Orange (4월은 너의 거짓말)'],
    ['Crossing Field LiSA Sword Art Online', 'LiSA - Crossing Field (소드 아트 온라인)'],
    ['Oath Sign LiSA Fate Zero', 'LiSA - oath sign (페이트 제로)'],
    ['Aimer Brave Shine Fate Stay Night UBW', 'Aimer - Brave Shine (페이트 UBW)'],
    ['Cruel Angels Thesis Evangelion OP', '타카하시 요코 - 잔혹한 천사의 테제 (에반게리온)'],
    ['Fly Me To The Moon Evangelion ED', 'CLAIRE - Fly Me to the Moon (에반게리온)'],
    ['Cowboy Bebop Tank OP official', 'Seatbelts - Tank! (카우보이 비밥)'],
    ['Sailor Moon Moonlight Densetsu official', 'DALI - 문라이트 전설 (세일러문)'],
    ['Dragon Ball Z CHA-LA HEAD-CHA-LA', '카게야마 히로노부 - CHA-LA HEAD-CHA-LA (드래곤볼Z)'],
    ['Pokemon original theme song', '포켓몬스터 - 목표는 포켓몬 마스터'],
    ['Snow Halation Love Live', 'μ\'s - Snow halation (러브라이브)'],
    ['Connect ClariS Madoka Magica', 'ClariS - コネクト (마법소녀 마도카 마기카)'],
    ['Renai Circulation Bakemonogatari', '하나자와 카나 - 연애 서큘레이션 (바케모노가타리)'],
    ['Platinum Disco Nisemonogatari', '이구치 유카 - 플래티넘 디스코 (니세모노가타리)'],
    ['Hacking to the Gate Steins Gate OP', '이토 카나코 - Hacking to the Gate (슈타인즈 게이트)'],
    ['My Dearest Guilty Crown OP', 'supercell - My Dearest (길티크라운)'],
    ['Unravel Tokyo Ghoul piano cover', 'TK - unravel (도쿄 구울) Piano'],
    ['Black Catcher Black Clover OP', 'ビッケブランカ - Black Catcher (블랙 클로버)'],
    ['Kaen Dororo OP official', '여왕벌 - カエン (도로로)'],
    ['Shinzo Wo Sasageyo piano cover', '심장을 바쳐라 피아노 커버 (진격의 거인)'],
    ['One Punch Man hero official OP', 'JAM Project - THE HERO (원펀맨)'],
    ['Mob Choir 99 Mob Psycho 100', 'MOB CHOIR - 99 (몹 사이코 100)'],
    ['Beastars Wild Side ALI official', 'ALI - Wild Side (비스타즈)'],
    ['Jujutsu Kaisen Where Our Blue Is', 'Tatsuya Kitani - Where Our Blue Is (주술회전)'],
    ['Summertime Cinnamons official', 'cinnamons - summertime (틱톡 유명곡)'],
    ['Sparkle Official RADWIMPS live', 'RADWIMPS - 스파클 라이브 (너의 이름은.)'],
    ['Promise of the World Howls Moving Castle', '치무라 키미코 - 세계의 약속 (하울의 움직이는 성)'],
    ['Joe Hisaishi One Summers Day Spirited Away', '히사이시 조 - 어느 여름날 (센과 치히로)'],
    ['Merry Go Round of Life Howls Castle', '히사이시 조 - 인생의 회전목마 (하울)'],
    ['Kaze no Toori Michi Totoro', '히사이시 조 - 바람의 길 (토토로)'],
    ['Path of the Wind Totoro piano', '히사이시 조 - 산책길 (토토로)'],
    ['Laputa Castle in the Sky theme', '히사이시 조 - 하늘의 성 라퓨타 테마'],
    ['Princess Mononoke Theme Legend', '히사이시 조 - 모노노케 히메 (원령공주)'],
    ['Nausicaa Requiem Ghibli', '히사이시 조 - 나우시카 레퀴엠'],
    ['Ponyo on the Cliff theme', '히사이시 조 - 벼랑 위의 포뇨'],
    ['Demon Slayer Mugen Train theme', '귀멸의 칼날 무한열차 OST'],
    ['Attack on Titan Vogel im Kafig', 'Hiroyuki Sawano - Vogel im Käfig (진격의 거인)'],
    ['Attack on Titan ashes on fire', 'KOHTA YAMAMOTO - Ashes on The Fire (진격의 거인)'],
    ['My Hero Academia Peace Sign', '요네즈 켄시 - 피스 사인 (히로아카)'],
    ['My Hero Academia The Day', 'Porno Graffitti - THE DAY (히로아카)'],
    ['Vinland Saga Dark Crow', 'MAN WITH A MISSION - Dark Crow (빈란드 사가)'],
    ['Chainsaw Man KICK BACK MV official', '체인소 맨 OP - KICK BACK'],
    ['Dandadan Otonoke full MV', '단다단 OP - 오토노케'],
    ['Frieren Yoake no Uta', 'milet - 새벽의 노래 (장송의 프리렌)'],
    ['Solo Leveling MV LEvel official', 'SawanoHiroyuki - LEveL (나 혼자만 레벨업)'],
    ['One Piece We Are Straw Hat ver', '원피스 - We Are! (밀짚모자 버전)'],
    ['Naruto Sadness and Sorrow OST', '나루토 OST - Sadness and Sorrow'],
    ['Bleach Asterisk Opening 1', 'ORANGE RANGE - *~アスタリスク~ (블리치)'],
    ['Bleach Number One OST', '블리치 OST - Number One'],
    ['Death Note OP 1 official', 'ナイトメア - THE WORLD (데스노트)'],
    ['Code Geass COLORS FLOW', 'FLOW - COLORS (코드 기아스)'],
    ['Spy x Family Mixed Nuts full', '스파이 패밀리 OP - Mixed Nuts'],
    ['Tokyo Revengers Cry Baby OP', '히게단 - Cry Baby (도쿄 리벤저스)'],
    ['Bocchi the Rock Seishun Complex', '결속밴드 - 청춘 컴플렉스 (봇치 더 록)'],
    ['Bunny Girl Senpai Fukashigi no Carte', '후카시기노 카르테 (청춘 돼지 시리즈)'],
    ['Re Zero Paradisus Paradoxum', 'MYTH & ROID - Paradisus-Paradoxum (리제로)'],
    ['Konosuba Fantastic Dreamer', 'Machico - fantastic dreamer (코노스바)'],
    ['Dr Stone Good Morning World', 'BURNOUT SYNDROMES - Good Morning World (닥터 스톤)'],
    ['Oshi no Ko Sign MV YOASOBI', '요아소비 - Sign (최애의 아이 2기)'],
    ['Dandadan OP2 Bling Bang', '단다단 OP - Bling-Bang-Bang-Born'],
];
