// 2000년대 싸이월드 감성 인기곡 데이터 (검색어, 정답)
export const CYWORLD_SONGS = [
    // 2000년대 발라드 / 남성 솔로
    ['버즈 가시 official MV', '버즈 - 가시'],
    ['버즈 겁쟁이 official MV', '버즈 - 겁쟁이'],
    ['버즈 남자를 몰라 official', '버즈 - 남자를 몰라'],
    ['버즈 처음엔 official', '버즈 - 처음엔'],
    ['SG워너비 죄와 벌 official MV', 'SG워너비 - 죄와 벌'],
    ['SG워너비 내 사람 official', 'SG워너비 - 내 사람'],
    ['SG워너비 아리랑 official', 'SG워너비 - 아리랑'],
    ['SG워너비 한 여름날의 꿈 official', 'SG워너비 - 한 여름날의 꿈'],
    ['SG워너비 Timeless official', 'SG워너비 - Timeless'],
    ['김종국 사랑스러워 official MV', '김종국 - 사랑스러워'],
    ['김종국 제자리걸음 official MV', '김종국 - 제자리걸음'],
    ['이승기 내 여자라니까 official MV', '이승기 - 내 여자라니까'],
    ['이승기 결혼해줄래 official MV', '이승기 - 결혼해줄래'],
    ['이승기 되고 싶다 official MV', '이승기 - 되고 싶다'],
    ['MC몽 너에게 쓰는 편지 official', 'MC몽 - 너에게 쓰는 편지'],
    ['MC몽 서커스 official MV', 'MC몽 - 서커스'],
    ['MC몽 변하지 않는 것들 official', 'MC몽 - 변하지 않는 것들'],
    ['이적 Ayo official MV', '이적 - Ayo'],
    ['이적 다행이다 official MV', '이적 - 다행이다'],
    ['박효신 야생화 official MV', '박효신 - 야생화'],
    ['박효신 눈의꽃 official MV', '박효신 - 눈의 꽃'],
    ['박효신 I Love You official MV', '박효신 - I Love You'],
    ['이문세 붉은 노을 official', '이문세 - 붉은 노을'],
    ['조성모 To Heaven official MV', '조성모 - To Heaven'],
    ['조성모 아시나요 official MV', '조성모 - 아시나요'],
    ['성시경 거리에서 official MV', '성시경 - 거리에서'],
    ['성시경 두 사람 official MV', '성시경 - 두 사람'],
    ['성시경 넌 내게 반했어 official', '성시경 - 넌 내게 반했어'],
    ['변진섭 너에게로 또다시 official', '변진섭 - 너에게로 또다시'],
    ['윤도현 사랑했나봐 official MV', '윤도현밴드 - 사랑했나봐'],

    // 2000년대 여성 솔로 / 그룹
    ['아이유 좋은날 official MV', 'IU - 좋은날'],
    ['박정현 나만 알아요 official MV', '박정현 - 나만 알아요'],
    ['박정현 꿈에 official MV', '박정현 - 꿈에'],
    ['fly to the sky 남자답게 official', 'Fly To The Sky - 남자답게'],
    ['fly to the sky 우리 사랑 이대로 official', 'Fly To The Sky - 우리 사랑 이대로'],
    ['이수영 LA LA LA official MV', '이수영 - LA LA LA'],
    ['이수영 그런 사람 또 없습니다 official', '이수영 - 그런 사람 또 없습니다'],
    ['소녀시대 Genie official MV', '소녀시대 - Genie'],
    ['소녀시대 Into The New World official MV', '소녀시대 - 다시 만난 세계'],
    ['카라 Mr official MV', '카라 - Mr.'],
    ['카라 Honey official MV', '카라 - Honey'],
    ['Miss A Bad Girl Good Girl official MV', 'Miss A - Bad Girl Good Girl'],
    ['원더걸스 So Hot official MV', '원더걸스 - So Hot'],
    ['원더걸스 2 Different Tears official MV', '원더걸스 - 2 Different Tears'],
    ['f(x) La Cha Ta official MV', 'f(x) - NU ABO'],
    ['샤이니 산소같은 너 official MV', 'SHINee - 산소같은 너'],

    // 2000년대 남성 그룹
    ['동방신기 Hug official MV', '동방신기 - Hug'],
    ['동방신기 주문 official MV', '동방신기 - 주문-MIROTIC'],
    ['동방신기 왜 official MV', '동방신기 - 왜 (Keep Your Head Down)'],
    ['SS501 Never Let You Go official MV', 'SS501 - Never Let You Go'],
    ['SS501 U R Man official MV', 'SS501 - U R Man'],
    ['슈퍼주니어 쏘리쏘리 official MV', 'Super Junior - Sorry, Sorry'],
    ['슈퍼주니어 Mr. Simple official MV', 'Super Junior - Mr. Simple'],
    ['2PM Heartbeat official MV', '2PM - Heartbeat'],
    ['2PM Again & Again official MV', '2PM - Again & Again'],
    ['2AM 죽어도 못 보내 official MV', '2AM - 죽어도 못 보내'],
    ['2AM 이 노래 official MV', '2AM - 이 노래'],
    ['빅뱅 거짓말 official MV', '빅뱅 - 거짓말'],
    ['빅뱅 마지막 인사 official MV', '빅뱅 - 마지막 인사'],
    ['빅뱅 하루하루 official MV', '빅뱅 - 하루하루'],
    ['빅뱅 붉은 노을 official MV', '빅뱅 - 붉은 노을'],
    ['SechsKies 세상 끝에서 official', '젝스키스 - 세상 끝에서'],
    ['god 어머님께 official MV', 'god - 어머님께'],
    ['god 길 official MV', 'god - 길'],
    ['신화 Perfect Man official MV', '신화 - Perfect Man'],
    ['H.O.T 캔디 official MV', 'H.O.T - 캔디'],
    ['H.O.T 행복 official MV', 'H.O.T - 행복'],

    // 힙합 / R&B
    ['에픽하이 Fly official MV', '에픽하이 - Fly'],
    ['에픽하이 우산 official MV', '에픽하이 - 우산'],
    ['에픽하이 One official MV', '에픽하이 - One'],
    ['에픽하이 Fan official MV', '에픽하이 - Fan'],
    ['리쌍 부탁해 official MV', '리쌍 - 부탁해'],
    ['리쌍 눈물이 있어 official MV', '리쌍 - 눈물이 있어'],
    ['스윗소로우 봄날에 official', '스윗소로우 - 봄날에'],
    ['박재범 나쁜기집애 official MV', '박재범 - 나쁜기집애'],

    // 중후반부 발라드
    ['V.O.S 사랑한다 말할걸 official', 'V.O.S - 사랑한다 말할걸'],
    ['V.O.S 눈물을 보고 말해요 official', 'V.O.S - 눈을 보고 말해요'],
    ['바이브 그남자 그여자 official MV', '바이브 - 그남자 그여자'],
    ['바이브 가슴이 시려 official MV', '바이브 - 가슴이 시려'],
    ['바이브 술이야 official MV', '바이브 - 술이야'],
    ['임재범 고해 official MV', '임재범 - 고해'],
    ['임재범 이 밤이 지나면 official MV', '임재범 - 이 밤이 지나면'],
    ['이하이 1,2,3,4 official MV', '이하이 - 1,2,3,4'],

    // 2000년대 대표 통통 튀는 팝
    ['프리스타일 Y official MV', '프리스타일 - Y'],
    ['거미 기억상실 official MV', '거미 - 기억상실'],
    ['거미 친구라도 될 걸 그랬어 official MV', '거미 - 친구라도 될 걸 그랬어'],
    ['거미 You are my lady official MV', '거미 - You are my lady'],
    ['브라운 아이드 걸스 Abracadabra official MV', '브라운 아이드 걸스 - Abracadabra'],
    ['브라운 아이드 걸스 Sign official MV', '브라운 아이드 걸스 - Sign'],
    ['강타 이별이 오고 official MV', '강타 - 이별이 오고'],
    ['장나라 Sweet Dream official MV', '장나라 - Sweet Dream'],
    ['유리상자 사랑해도 될까요 official MV', '유리상자 - 사랑해도 될까요'],
    ['럼블피쉬 비가 온다 official MV', '럼블피쉬 - 비가 온다'],
    ['럼블피쉬 자꾸 그대로 official', '럼블피쉬 - 자꾸 그대로'],
    ['레이지본 사랑앓이 official MV', '레이지본 - 사랑앓이'],
    ['제이 나보다 조금 더 높은 곳에 있는 너 official', '제이 - 나보다 조금 더 높은 곳에 있는 너'],
    ['김범수 보고싶다 official MV', '김범수 - 보고싶다'],
    ['김범수 벌써일년 official MV', '김범수 - 벌써 일년'],
    ['화요비 가슴아 official MV', '화요비 - 가슴아'],
    ['은지원 Bounce official MV', '은지원 - Bounce'],
    ['강다니엘 Jealous official MV', '강다니엘 - Jealous'],
    ['태양 나만봐 official MV', '태양 - 나만봐'],
    ['지드래곤 삐딱하게 official MV', 'G-DRAGON - 삐딱하게'],
    ['빅뱅 blue official MV', '빅뱅 - BLUE'],
    ['초신성 투명인간 official MV', '초신성 - 투명인간'],
    ['2NE1 나쁜 기억 지워 official MV', '2NE1 - 나쁜 기억 지워'],
    ['2NE1 Go Away official MV', '2NE1 - Go Away'],
    ['나얼 바람기억 official MV', '나얼 - 바람기억'],
    ['나얼 같은 시간 속의 너 official MV', '나얼 - 같은 시간 속의 너'],
    ['한동근 이 사람이다 official MV', '한동근 - 이 사람이다'],
    ['씨야 남자는 다 나빠 official MV', '씨야 - 남자는 다 나빠'],
    ['씨야 사랑의 인사 official MV', '씨야 - 사랑의 인사'],
    ['다비치 8282 official MV', '다비치 - 8282'],
    ['다비치 사랑과 전쟁 official MV', '다비치 - 사랑과 전쟁'],
    ['다비치 위아래 official MV', '다비치 - 위아래'],
    ['린 기억을 걷는 시간 official MV', '린 - 기억을 걷는 시간'],
    ['린 사랑인가요 official MV', '린 - 사랑인가요'],
    ['에일리 보여줄게 official MV', '에일리 - 보여줄게'],
    ['에일리 Invitation official MV', '에일리 - Invitation'],
    ['더 이스트라이트 니가 없어서 official MV', '더 이스트라이트 - 니가 없어서'],
    ['가요톱10 현진영 흐린 기억 속의 그대 official', '현진영 - 흐린 기억 속의 그대'],
    ['이수영 모르나요 official MV', '이수영 - 모르나요'],
];
