// Game BGM quiz seed data
export const GAME_SONGS = [
    ['Minecraft Sweden C418 official', 'C418 - Sweden (마인크래프트)'],
    ['Minecraft Wet Hands C418', 'C418 - Wet Hands (마인크래프트)'],
    ['Minecraft Subwoofer Lullaby C418', 'C418 - Subwoofer Lullaby (마인크래프트)'],
    ['Undertale Megalovania official', 'Toby Fox - MEGALOVANIA (언더테일)'],
    ['Undertale His Theme official', 'Toby Fox - His Theme (언더테일)'],
    ['Undertale Hopes and Dreams OST', 'Toby Fox - Hopes and Dreams (언더테일)'],
    ['Deltarune THE WORLD REVOLVING', 'Toby Fox - THE WORLD REVOLVING (델타룬)'],
    ['Super Mario Bros Theme piano cover', '슈퍼마리오 - 메인 테마 피아노'],
    ['Super Mario 64 Bob Omb Battlefield', '슈퍼마리오64 - 폭탄병 전장 브금'],
    ['Mario Kart Coconut Mall music', '마리오 카트 - 코코넛 몰 브금'],
    ['Legend of Zelda Main Theme piano', '젤다의 전설 - 메인 테마 피아노'],
    ['Legend of Zelda Song of Storms', '젤다의 전설 - 폭풍의 노래'],
    ['Zelda Breath of Wild Main Theme', '젤다 야숨 - 메인 테마'],
    ['Zelda Tears of Kingdom theme', '젤다 티어스 - 메인 테마'],
    ['Animal Crossing Main Theme piano', '동물의 숲 - 메인 테마 피아노'],
    ['Animal Crossing KK Bubblegum', '동물의 숲 - KK 버블검'],
    ['Pokemon Red Blue Battle Theme remix', '포켓몬스터 - 전투 테마 리믹스'],
    ['Pokemon Center Theme piano', '포켓몬 센터 - 회복 브금 피아노'],
    ['Pokemon Lavender Town Theme', '포켓몬 - 보라타운 브금'],
    ['Pokemon Route 1 Theme piano', '포켓몬 - 1번 도로 피아노'],
    ['Kirby Green Greens piano cover', '별의 커비 - 그린 그린즈 피아노'],
    ['Kirby Gourmet Race theme piano', '별의 커비 - 미식 레이스 피아노'],
    ['Tetris Theme A Korobeiniki piano', '테트리스 - 테마A 피아노'],
    ['Pac Man theme original', '팩맨 - 오리지널 테마'],
    ['Sonic Green Hill Zone piano', '소닉 - 그린힐존 피아노'],
    ['Sonic City Escape piano', '소닉 어드벤처2 - City Escape'],
    ['Final Fantasy Victory Fanfare piano', '파이널 판타지 - 승리 팡파레 피아노'],
    ['Final Fantasy VII Main Theme piano', 'FF7 - 메인 테마 피아노'],
    ['Final Fantasy Prelude piano', '파이널 판타지 - Prelude 피아노'],
    ['Chrono Trigger Main Theme piano', '크로노 트리거 - 메인 테마 피아노'],
    ['Chrono Cross Time Scar piano', '크로노 크로스 - Time\'s Scar 피아노'],
    ['NieR Automata Weight of the World', '니어 오토마타 - Weight of the World'],
    ['NieR Automata City Ruins', '니어 오토마타 - 폐허 도시 (City Ruins)'],
    ['NieR Automata Amusement Park', '니어 오토마타 - 유원지 (Amusement Park)'],
    ['Kingdom Hearts Dearly Beloved piano', '킹덤하츠 - Dearly Beloved 피아노'],
    ['Kingdom Hearts Simple and Clean', '우타다 히카루 - Simple and Clean (킹덤하츠)'],
    ['Hollow Knight Main Theme piano', '할로우 나이트 - 메인 테마 피아노'],
    ['Hollow Knight City of Tears', '할로우 나이트 - City of Tears'],
    ['Celeste First Steps piano', '셀레스테 - First Steps 피아노'],
    ['Cuphead Floral Fury', '컵헤드 - Floral Fury'],
    ['Cuphead Die House', '컵헤드 - Die House'],
    ['Stardew Valley Spring Theme', '스타듀밸리 - 봄 테마'],
    ['Stardew Valley Summer Theme', '스타듀밸리 - 여름 테마'],
    ['Hades Good Riddance', '하데스 - Good Riddance'],
    ['Hades In the Blood', '하데스 - In the Blood'],
    ['Ori and the Blind Forest Main Theme', '오리와 눈먼 숲 - 메인 테마'],
    ['Dark Souls Main Theme piano', '다크 소울 - 메인 테마 피아노'],
    ['Dark Souls Gwyn Lord of Cinder', '다크 소울 - 태양의 왕 그윈 피아노'],
    ['Elden Ring Main Theme piano', '엘든 링 - 메인 테마 피아노'],
    ['Bloodborne Ludwig Theme', '블러드본 - 루드비히 테마'],
    ['Ghost of Tsushima Main Theme', '고스트 오브 쓰시마 - 메인 테마'],
    ['Genshin Impact Main Theme piano', '원신 - 메인 테마 피아노'],
    ['Genshin Impact Liyue Battle Theme', '원신 - 리월 전투 브금'],
    ['Genshin Impact Inazuma Theme', '원신 - 이나즈마 테마'],
    ['Persona 5 Last Surprise', '페르소나5 - Last Surprise'],
    ['Persona 5 Rivers in the Desert', '페르소나5 - Rivers in the Desert'],
    ['Persona 5 Beneath the Mask', '페르소나5 - Beneath the Mask'],
    ['Persona 4 Reach Out to the Truth', '페르소나4 - Reach Out To The Truth'],
    ['Persona 3 Burn My Dread', '페르소나3 - Burn My Dread'],
    ['Metal Gear Solid Theme piano', '메탈기어 솔리드 - 메인 테마 피아노'],
    ['Skyrim Dragonborn piano', '스카이림 - Dragonborn 피아노'],
    ['Witcher 3 Toss a Coin cover', '위쳐3 - Toss a Coin 커버'],
    ['Doom Eternal BFG Division', '둠 이터널 - BFG Division'],
    ['Doom Eternal The Only Thing They Fear Is You', '둠 이터널 - The Only Thing They Fear Is You'],
    ['Halo Theme piano cover', '헤일로 - 메인 테마 피아노'],
    ['God of War Main Theme piano', '갓 오브 워 - 메인 테마 피아노'],
    ['Red Dead Redemption 2 Thats the Way It Is', 'RDR2 - That\'s The Way It Is'],
    ['GTA San Andreas Theme piano', 'GTA 산안 - 메인 테마 피아노'],
    ['Assassins Creed 2 Ezios Family piano', 'AC2 - Ezio\'s Family 피아노'],
    ['Wii Sports Theme piano cover', 'Wii 스포츠 - 테마 피아노'],
    ['Wii Channel Theme piano', 'Wii - Mii 채널 테마 피아노'],
    ['Rise of Kingdoms piano cover', '라이즈 오브 킹덤즈 - 테마'],
    ['League of Legends Worlds Collide', 'LoL - Worlds Collide'],
    ['League of Legends Warriors Imagine Dragons', 'LoL - Warriors (롤 시즌 2020)'],
    ['League of Legends RISE Worlds 2018', 'LoL - RISE (롤 월즈 2018)'],
    ['League of Legends POP STARS KDA', 'K/DA - POP/STARS (리그 오브 레전드)'],
    ['League of Legends MORE KDA', 'K/DA - MORE (리그 오브 레전드)'],
    ['League of Legends Legends Never Die', 'LoL - Legends Never Die'],
    ['Overwatch Main Theme piano', '오버워치 - 메인 테마 피아노'],
    ['Valorant Main Theme', '발로란트 - 메인 테마'],
    ['Fortnite OG lobby music', '포트나이트 - OG 로비 브금'],
    ['Among Us Theme Drip remix', '어몽어스 - 드립 리믹스'],
    ['MapleStory Login Theme piano cover', '메이플스토리 - 로그인 테마 피아노'],
    ['MapleStory Ellinia BGM piano', '메이플스토리 - 엘리니아 브금 피아노'],
    ['MapleStory Lith Harbor BGM piano', '메이플스토리 - 리스항구 브금 피아노'],
    ['MapleStory Henesys BGM piano', '메이플스토리 - 헤네시스 피아노'],
    ['Crazy Arcade BGM piano', '크레이지아케이드 - 로비 브금 피아노'],
    ['Kart Rider BGM piano cover', '카트라이더 - 로비 브금 피아노'],
    ['Kartrider Drift Theme', '카트라이더 - 드리프트 테마'],
    ['Mabinogi Login BGM piano', '마비노기 - 로그인 테마 피아노'],
    ['Dungeon Fighter Online BGM piano', '던전앤파이터 - 세리아의 방 피아노'],
    ['Lost Ark Main Theme piano', '로스트아크 - 메인 테마 피아노'],
    ['Black Desert Online theme piano', '검은사막 - 메인 테마 피아노'],
    ['Starcraft Terran Theme 1 piano', '스타크래프트 - 테란 테마1 피아노'],
    ['Diablo Tristram Theme piano', '디아블로 - 트리스트럼 테마 피아노'],
    ['World of Warcraft Main Theme piano', '월드 오브 워크래프트 - 메인 테마 피아노'],
    ['Overwatch 2 Main Theme', '오버워치2 - 메인 테마'],
    ['Street Fighter 2 Guile Theme piano', '스트리트 파이터2 - 가일 테마 피아노'],
    ['Mortal Kombat Theme piano', '모탈 컴뱃 - 메인 테마 피아노'],
];
