// J-POP 100 quiz seed data
// Each entry: [search query, correct answer text]
export const JPOP_SONGS = [
    ['YOASOBI Idol official', '요아소비 - 아이돌 (Idol)'],
    ['YOASOBI Racing into the Night official', '요아소비 - 밤을 달리다 (Yoru ni Kakeru)'],
    ['Kenshi Yonezu Lemon MV', '요네즈 켄시 - Lemon'],
    ['Kenshi Yonezu KICK BACK MV', '요네즈 켄시 - KICK BACK'],
    ['Kenshi Yonezu Peace Sign MV', '요네즈 켄시 - 피스 사인'],
    ['Aimyon Marigold official', '아이묭 - 마리골드'],
    ['Aimyon Harunohi MV', '아이묭 - 하루노히'],
    ['imase NIGHT DANCER official', '이마세 - NIGHT DANCER'],
    ['LiSA Gurenge official', 'LiSA - 홍련화 (Gurenge)'],
    ['LiSA Homura official MV', 'LiSA - 불꽃 (Homura)'],
    ['LiSA Zankyosanka MV', 'LiSA - 잔향산가'],
    ['Official HIGE DANdism Pretender MV', '히게단 - Pretender'],
    ['Official HIGE DANdism Mixed Nuts MV', '히게단 - Mixed Nuts'],
    ['Official HIGE DANdism Subtitle MV', '히게단 - Subtitle'],
    ['Official HIGE DANdism Cry Baby MV', '히게단 - Cry Baby'],
    ['Fujii Kaze Shinunoga E-Wa official', '후지이 카제 - 死ぬのがいいわ'],
    ['Fujii Kaze Matatabi official', '후지이 카제 - Matatabi'],
    ['RADWIMPS Sparkle official', 'RADWIMPS - 스파클 (Sparkle)'],
    ['RADWIMPS Zenzenzense official', 'RADWIMPS - 전전전세'],
    ['RADWIMPS Nandemonaiya official', 'RADWIMPS - 아무것도 아니야'],
    ['Ado Odo official', 'Ado - 踊 (Odo)'],
    ['Ado Usseewa official', 'Ado - うっせぇわ'],
    ['Ado Show official', 'Ado - Show'],
    ['Ado New Genesis official', 'Ado - 新時代 (New Genesis)'],
    ['Eve Kaikai Kitan official', 'Eve - 廻廻奇譚'],
    ['Eve Dramaturgy official', 'Eve - ドラマツルギー'],
    ['Yorushika Say It official', 'ヨルシカ - 言って。'],
    ['Yorushika Haru Dorobou official', 'ヨルシカ - 春泥棒'],
    ['Mrs GREEN APPLE Inferno official', 'Mrs. GREEN APPLE - インフェルノ'],
    ['Mrs GREEN APPLE Que Sera Sera official', 'Mrs. GREEN APPLE - ケセラセラ'],
    ['Mrs GREEN APPLE Columba official', 'Mrs. GREEN APPLE - コロンブス'],
    ['King Gnu Hakujitsu official', 'King Gnu - 白日'],
    ['King Gnu Ichizu official', 'King Gnu - 一途'],
    ['King Gnu BOY official', 'King Gnu - BOY'],
    ['Creepy Nuts Bling Bang Bang Born official', 'Creepy Nuts - Bling-Bang-Bang-Born'],
    ['back number Christmas Song official', 'back number - クリスマスソング'],
    ['back number Happy Birthday official', 'back number - Happy Birthday'],
    ['back number Suiheisen official', 'back number - 水平線'],
    ['Vaundy Odoriko official', 'Vaundy - 踊り子'],
    ['Vaundy Kaiju no Hanauta official', 'Vaundy - 怪獣の花唄'],
    ['Vaundy Hadaka no Yuusha official', 'Vaundy - 裸の勇者'],
    ['Yuuri Betelgeuse official', '優里 - ベテルギウス'],
    ['Yuuri Dry Flower official', '優里 - ドライフラワー'],
    ['BUMP OF CHICKEN Tentai Kansoku official', 'BUMP OF CHICKEN - 天体観測'],
    ['BUMP OF CHICKEN Souvenir official', 'BUMP OF CHICKEN - SOUVENIR'],
    ['ONE OK ROCK The Beginning official', 'ONE OK ROCK - The Beginning'],
    ['ONE OK ROCK Wherever You Are official', 'ONE OK ROCK - Wherever you are'],
    ['Aimer Zankyou Sanka official', 'Aimer - 残響散歌'],
    ['Aimer Brave Shine official', 'Aimer - Brave Shine'],
    ['Aimer Kataomoi official', 'Aimer - カタオモイ'],
    ['milet inside you official', 'milet - inside you'],
    ['TWICE Kura Kura official', 'TWICE - Kura Kura'],
    ['Spitz Robinson official', 'スピッツ - ロビンソン'],
    ['Spitz Sora mo Toberu official', 'スピッツ - 空も飛べるはず'],
    ['Mr Children Tomorrow never knows official', 'Mr.Children - Tomorrow never knows'],
    ['Mr Children Hanabi official', 'Mr.Children - HANABI'],
    ['Higedan I LOVE official', '히게단 - I LOVE...'],
    ['Ikimonogakari SAKURA official', '이키모노가카리 - SAKURA'],
    ['Ikimonogakari Blue Bird official', '이키모노가카리 - ブルーバード'],
    ['GReeeeN Kiseki official', 'GReeeeN - キセキ'],
    ['Asian Kung-Fu Generation Rewrite official', 'AKFG - リライト (Rewrite)'],
    ['Asian Kung-Fu Generation Haruka Kanata official', 'AKFG - 遥か彼方'],
    ['TK from Ling Tosite Sigure Unravel official', 'TK - unravel'],
    ['SiM The Rumbling official', 'SiM - The Rumbling'],
    ['FLOW GO official Naruto', 'FLOW - GO!!!'],
    ['Linked Horizon Shinzou wo Sasageyo official', 'Linked Horizon - 心臓を捧げよ'],
    ['Linked Horizon Guren no Yumiya official', 'Linked Horizon - 紅蓮の弓矢'],
    ['SPYAIR Imagination official', 'SPYAIR - イマジネーション'],
    ['Suzume Soundtrack RADWIMPS', 'RADWIMPS - すずめ (Suzume)'],
    ['Aimer Kessui official', 'Aimer - 蝶々結び'],
    ['Yama Haru wo Tsugeru official', 'yama - 春を告げる'],
    ['Tatsuya Kitani Seija no Koushin official', 'キタニタツヤ - 聖者の行進'],
    ['10-FEET Dai Zero Kan official', '10-FEET - 第ゼロ感'],
    ['Kenshi Yonezu Shunrai official', '요네즈 켄시 - SHUNRAI'],
    ['Kenshi Yonezu Pale Blue official', '요네즈 켄시 - Pale Blue'],
    ['Ado Tot Musica official', 'Ado - Tot Musica'],
    ['Ado Readymade official', 'Ado - レディメイド'],
    ['YOASOBI The Blessing official', '요아소비 - 祝福 (The Blessing)'],
    ['YOASOBI Gunjo official', '요아소비 - 群青 (Gunjou)'],
    ['YOASOBI Tabun official', '요아소비 - たぶん'],
    ['Fujii Kaze Kirari official', '후지이 카제 - きらり'],
    ['King Gnu Samayu official', 'King Gnu - SPECIALZ'],
    ['Creepy Nuts Otonoke official', 'Creepy Nuts - オトノケ'],
    ['Ado Gira Gira official', 'Ado - ギラギラ'],
    ['Eve Shinkai official', 'Eve - 心海'],
    ['Kenshi Yonezu Flamingo official', '요네즈 켄시 - Flamingo'],
    ['Kenshi Yonezu Uma to Shika official', '요네즈 켄시 - 馬と鹿'],
    ['Sayuri Mikazuki official', 'さユり - ミカヅキ'],
    ['Yorushika Dakara Boku wa official', 'ヨルシカ - だから僕は音楽を辞めた'],
    ['Aimyon Ai wo Tsutaetai datoka official', '아이묭 - 愛を伝えたいだとか'],
    ['Vaundy Napori official', 'Vaundy - napori'],
    ['XG Tippy Toes official', 'XG - Tippy Toes'],
    ['Fujii Kaze Workin Hard official', '후지이 카제 - Workin\' Hard'],
    ['YOASOBI Yuusha official', '요아소비 - 勇者 (Yuusha)'],
    ['Ado Ama Amagami official', 'Ado - 愛して愛して愛して'],
    ['BE FIRST Smile Again official', 'BE:FIRST - Smile Again'],
    ['Naniwa Danshi Shiranai official', 'なにわ男子 - サチアレ'],
    ['Tani Yuuki W official', 'tani yuuki - W/X/Y'],
    ['Official HIGE DANdism Hello official', '히게단 - Hello'],
];
