// K-POP quiz seed data (replaces Cyworld BGM + LoL categories with broader K-POP)
export const KPOP_SONGS = [
    ['BTS Dynamite official MV', 'BTS - Dynamite'],
    ['BTS Butter official MV', 'BTS - Butter'],
    ['BTS Boy With Luv official MV', 'BTS - 작은 것들을 위한 시 (Boy With Luv)'],
    ['BTS Spring Day official MV', 'BTS - 봄날 (Spring Day)'],
    ['BTS DNA official MV', 'BTS - DNA'],
    ['BTS Blood Sweat Tears official MV', 'BTS - 피 땀 눈물'],
    ['BTS IDOL official MV', 'BTS - IDOL'],
    ['BTS Fake Love official MV', 'BTS - FAKE LOVE'],
    ['BTS MIC Drop official MV', 'BTS - MIC Drop'],
    ['BTS Permission to Dance official', 'BTS - Permission to Dance'],
    ['BLACKPINK DDU DU DDU DU official', 'BLACKPINK - 뚜두뚜두'],
    ['BLACKPINK How You Like That official', 'BLACKPINK - How You Like That'],
    ['BLACKPINK Kill This Love official', 'BLACKPINK - Kill This Love'],
    ['BLACKPINK Pink Venom official', 'BLACKPINK - Pink Venom'],
    ['BLACKPINK Shut Down official', 'BLACKPINK - Shut Down'],
    ['BLACKPINK Lovesick Girls official', 'BLACKPINK - Lovesick Girls'],
    ['NewJeans Hype Boy official', 'NewJeans - Hype Boy'],
    ['NewJeans Ditto official', 'NewJeans - Ditto'],
    ['NewJeans Super Shy official', 'NewJeans - Super Shy'],
    ['NewJeans Attention official', 'NewJeans - Attention'],
    ['NewJeans OMG official', 'NewJeans - OMG'],
    ['NewJeans ETA official', 'NewJeans - ETA'],
    ['aespa Next Level official', 'aespa - Next Level'],
    ['aespa Savage official', 'aespa - Savage'],
    ['aespa Supernova official', 'aespa - Supernova'],
    ['IVE LOVE DIVE official', 'IVE - LOVE DIVE'],
    ['IVE After LIKE official', 'IVE - After LIKE'],
    ['IVE I AM official', 'IVE - I AM'],
    ['LE SSERAFIM ANTIFRAGILE official', 'LE SSERAFIM - ANTIFRAGILE'],
    ['LE SSERAFIM UNFORGIVEN official', 'LE SSERAFIM - UNFORGIVEN'],
    ['LE SSERAFIM EASY official', 'LE SSERAFIM - EASY'],
    ['LE SSERAFIM Perfect Night official', 'LE SSERAFIM - Perfect Night'],
    ['TWICE Cheer Up official', 'TWICE - CHEER UP'],
    ['TWICE TT official MV', 'TWICE - TT'],
    ['TWICE What is Love official', 'TWICE - What is Love?'],
    ['TWICE Feel Special official', 'TWICE - Feel Special'],
    ['TWICE Fancy official', 'TWICE - FANCY'],
    ['TWICE Dance The Night Away official', 'TWICE - Dance The Night Away'],
    ['Red Velvet Psycho official', 'Red Velvet - Psycho'],
    ['Red Velvet Bad Boy official', 'Red Velvet - Bad Boy'],
    ['Red Velvet Red Flavor official MV', 'Red Velvet - 빨간 맛 (Red Flavor)'],
    ['ITZY DALLA DALLA official', 'ITZY - 달라달라'],
    ['ITZY WANNABE official', 'ITZY - WANNABE'],
    ['Stray Kids God Menu official', 'Stray Kids - 神메뉴 (God\'s Menu)'],
    ['Stray Kids MANIAC official', 'Stray Kids - MANIAC'],
    ['Stray Kids S-Class official', 'Stray Kids - 특 (S-Class)'],
    ['EXO Love Shot official', 'EXO - Love Shot'],
    ['EXO Monster official', 'EXO - Monster'],
    ['EXO Growl official', 'EXO - 으르렁 (Growl)'],
    ['SEVENTEEN Super official', 'SEVENTEEN - 손오공'],
    ['SEVENTEEN Very Nice official', 'SEVENTEEN - 아주 NICE'],
    ['SEVENTEEN HOT official', 'SEVENTEEN - HOT'],
    ['NCT DREAM Hot Sauce official', 'NCT DREAM - 맛 (Hot Sauce)'],
    ['NCT 127 Sticker official', 'NCT 127 - Sticker'],
    ['TXT Sugar Rush Ride official', 'TXT - Sugar Rush Ride'],
    ['TXT 0X1 LOVESONG official', 'TXT - 0X1=LOVESONG'],
    ['ENHYPEN Drunk Dazed official', 'ENHYPEN - Drunk-Dazed'],
    ['ATEEZ Guerrilla official', 'ATEEZ - Guerrilla'],
    ['TREASURE JIKJIN official', 'TREASURE - 직진 (JIKJIN)'],
    ['PSY Gangnam Style official MV', 'PSY - 강남스타일'],
    ['PSY Gentleman official', 'PSY - GENTLEMAN'],
    ['BIGBANG Fantastic Baby official', 'BIGBANG - FANTASTIC BABY'],
    ['BIGBANG Bang Bang Bang official', 'BIGBANG - 뱅뱅뱅'],
    ['2NE1 I Am The Best official', '2NE1 - 내가 제일 잘 나가'],
    ['Girls Generation Gee official', '소녀시대 - Gee'],
    ['Girls Generation I Got A Boy official', '소녀시대 - I GOT A BOY'],
    ['Wonder Girls Tell Me official', '원더걸스 - Tell Me'],
    ['Wonder Girls Nobody official', '원더걸스 - Nobody'],
    ['SHINee Ring Ding Dong official', 'SHINee - Ring Ding Dong'],
    ['SHINee Lucifer official', 'SHINee - Lucifer'],
    ['2PM Heartbeat official', '2PM - Heartbeat'],
    ['Super Junior Sorry Sorry official', 'Super Junior - Sorry, Sorry'],
    ['Super Junior Mr Simple official', 'Super Junior - Mr. Simple'],
    ['KARA Step official', 'KARA - Step'],
    ['SISTAR Loving U official', 'SISTAR - Loving U'],
    ['T-ARA Roly Poly official', 'T-ARA - Roly-Poly'],
    ['f(x) Electric Shock official', 'f(x) - Electric Shock'],
    ['MOMOLAND BBoom BBoom official', 'MOMOLAND - BBoom BBoom'],
    ['Zico Any Song official', '지코 - 아무노래'],
    ['IU Eight official', 'IU - 에잇 (Eight)'],
    ['IU Celebrity official', 'IU - Celebrity'],
    ['IU Blueming official', 'IU - 블루밍 (Blueming)'],
    ['IU Good Day official', 'IU - 좋은 날'],
    ['IU Palette official', 'IU - 팔레트 (Palette)'],
    ['AKMU How Can I Love official', '악뮤 - 어떻게 이별까지 사랑하겠어'],
    ['AKMU Dinosaur official', '악뮤 - 다이노소어'],
    ['Heize Happen official', '헤이즈 - 헤픈 우연'],
    ['DEAN Instagram official', '딘 - 인스타그램'],
    ['Jungkook Seven official', '정국 - Seven'],
    ['Jimin Like Crazy official', '지민 - Like Crazy'],
    ['V Slow Dancing official', '뷔 - Slow Dancing'],
    ['SUGA Agust D Daechwita official', '슈가 - 대취타'],
    ['Jennie SOLO official', '제니 - SOLO'],
    ['LISA LALISA official', '리사 - LALISA'],
    ['Rose APT official', '로제 - APT.'],
    ['Rose On The Ground official', '로제 - On The Ground'],
    ['G DRAGON Untitled 2014 official', 'G-DRAGON - 무제 (Untitled, 2014)'],
    ['MAMAMOO HIP official', 'MAMAMOO - HIP'],
    ['GFriend Rough official', '여자친구 - 시간을 달려서 (Rough)'],
    ['OH MY GIRL Nonstop official', 'OH MY GIRL - 살짝 설렜어 (Nonstop)'],
];
