// Billboard / Pop quiz seed data
export const POP_SONGS = [
    ['Ed Sheeran Shape of You official', 'Ed Sheeran - Shape of You'],
    ['Ed Sheeran Perfect official', 'Ed Sheeran - Perfect'],
    ['Ed Sheeran Thinking Out Loud official', 'Ed Sheeran - Thinking Out Loud'],
    ['Ed Sheeran Photograph official', 'Ed Sheeran - Photograph'],
    ['Ed Sheeran Bad Habits official', 'Ed Sheeran - Bad Habits'],
    ['The Kid LAROI Justin Bieber STAY official', 'Justin Bieber - STAY'],
    ['Justin Bieber Peaches official', 'Justin Bieber - Peaches'],
    ['Justin Bieber Baby official', 'Justin Bieber - Baby'],
    ['Charlie Puth Attention official', 'Charlie Puth - Attention'],
    ['Charlie Puth We Dont Talk Anymore official', 'Charlie Puth - We Dont Talk Anymore'],
    ['Charlie Puth See You Again official', 'Charlie Puth - See You Again'],
    ['Maroon 5 Sugar official', 'Maroon 5 - Sugar'],
    ['Maroon 5 Memories official', 'Maroon 5 - Memories'],
    ['Maroon 5 Girls Like You official', 'Maroon 5 - Girls Like You'],
    ['Bruno Mars That What I Like official', 'Bruno Mars - Thats What I Like'],
    ['Bruno Mars Uptown Funk official', 'Bruno Mars - Uptown Funk'],
    ['Bruno Mars 24K Magic official', 'Bruno Mars - 24K Magic'],
    ['Bruno Mars Just The Way You Are official', 'Bruno Mars - Just The Way You Are'],
    ['Bruno Mars Grenade official', 'Bruno Mars - Grenade'],
    ['The Weeknd Blinding Lights official', 'The Weeknd - Blinding Lights'],
    ['The Weeknd Starboy official', 'The Weeknd - Starboy'],
    ['The Weeknd Save Your Tears official', 'The Weeknd - Save Your Tears'],
    ['The Weeknd Die For You official', 'The Weeknd - Die For You'],
    ['Dua Lipa Levitating official', 'Dua Lipa - Levitating'],
    ['Dua Lipa Dont Start Now official', 'Dua Lipa - Dont Start Now'],
    ['Dua Lipa New Rules official', 'Dua Lipa - New Rules'],
    ['Harry Styles As It Was official', 'Harry Styles - As It Was'],
    ['Harry Styles Watermelon Sugar official', 'Harry Styles - Watermelon Sugar'],
    ['Adele Easy On Me official', 'Adele - Easy On Me'],
    ['Adele Rolling in the Deep official', 'Adele - Rolling in the Deep'],
    ['Adele Someone Like You official', 'Adele - Someone Like You'],
    ['Adele Hello official', 'Adele - Hello'],
    ['Taylor Swift Anti Hero official', 'Taylor Swift - Anti-Hero'],
    ['Taylor Swift Shake It Off official', 'Taylor Swift - Shake It Off'],
    ['Taylor Swift Blank Space official', 'Taylor Swift - Blank Space'],
    ['Taylor Swift Love Story official', 'Taylor Swift - Love Story'],
    ['Taylor Swift Cruel Summer official', 'Taylor Swift - Cruel Summer'],
    ['Billie Eilish Bad Guy official', 'Billie Eilish - bad guy'],
    ['Billie Eilish Lovely official', 'Billie Eilish - lovely'],
    ['Billie Eilish Happier Than Ever official', 'Billie Eilish - Happier Than Ever'],
    ['Olivia Rodrigo drivers license official', 'Olivia Rodrigo - drivers license'],
    ['Olivia Rodrigo good 4 u official', 'Olivia Rodrigo - good 4 u'],
    ['Olivia Rodrigo Vampire official', 'Olivia Rodrigo - vampire'],
    ['Imagine Dragons Believer official', 'Imagine Dragons - Believer'],
    ['Imagine Dragons Radioactive official', 'Imagine Dragons - Radioactive'],
    ['Imagine Dragons Thunder official', 'Imagine Dragons - Thunder'],
    ['Post Malone Sunflower official', 'Post Malone - Sunflower'],
    ['Post Malone Circles official', 'Post Malone - Circles'],
    ['Lewis Capaldi Someone You Loved official', 'Lewis Capaldi - Someone You Loved'],
    ['Glass Animals Heat Waves official', 'Glass Animals - Heat Waves'],
    ['Doja Cat Say So official', 'Doja Cat - Say So'],
    ['Doja Cat Kiss Me More official', 'Doja Cat - Kiss Me More'],
    ['SZA Kill Bill official', 'SZA - Kill Bill'],
    ['Miley Cyrus Flowers official', 'Miley Cyrus - Flowers'],
    ['Miley Cyrus Wrecking Ball official', 'Miley Cyrus - Wrecking Ball'],
    ['Sam Smith Unholy official', 'Sam Smith - Unholy'],
    ['Sam Smith Stay With Me official', 'Sam Smith - Stay With Me'],
    ['Shawn Mendes Senorita official', 'Shawn Mendes - Señorita'],
    ['Shawn Mendes Stitches official', 'Shawn Mendes - Stitches'],
    ['Shawn Mendes Treat You Better official', 'Shawn Mendes - Treat You Better'],
    ['One Direction Night Changes official', 'One Direction - Night Changes'],
    ['One Direction Story of My Life official', 'One Direction - Story of My Life'],
    ['Sia Cheap Thrills official', 'Sia - Cheap Thrills'],
    ['Sia Chandelier official', 'Sia - Chandelier'],
    ['Ariana Grande 7 rings official', 'Ariana Grande - 7 rings'],
    ['Ariana Grande Thank U Next official', 'Ariana Grande - thank u, next'],
    ['Ariana Grande positions official', 'Ariana Grande - positions'],
    ['Drake One Dance official', 'Drake - One Dance'],
    ['Lil Nas X Old Town Road official', 'Lil Nas X - Old Town Road'],
    ['Lil Nas X MONTERO official', 'Lil Nas X - MONTERO'],
    ['Cardi B WAP official', 'Cardi B - WAP'],
    ['Lizzo About Damn Time official', 'Lizzo - About Damn Time'],
    ['Lady Gaga Shallow official', 'Lady Gaga - Shallow'],
    ['Lady Gaga Bad Romance official', 'Lady Gaga - Bad Romance'],
    ['Rihanna Umbrella official', 'Rihanna - Umbrella'],
    ['Rihanna We Found Love official', 'Rihanna - We Found Love'],
    ['Beyonce CUFF IT official', 'Beyoncé - CUFF IT'],
    ['Beyonce Halo official', 'Beyoncé - Halo'],
    ['Katy Perry Roar official', 'Katy Perry - Roar'],
    ['Katy Perry Firework official', 'Katy Perry - Firework'],
    ['Coldplay Viva La Vida official', 'Coldplay - Viva la Vida'],
    ['Coldplay The Scientist official', 'Coldplay - The Scientist'],
    ['Coldplay Fix You official', 'Coldplay - Fix You'],
    ['Coldplay Yellow official', 'Coldplay - Yellow'],
    ['Coldplay My Universe official', 'Coldplay - My Universe'],
    ['John Legend All of Me official', 'John Legend - All of Me'],
    ['Pharrell Williams Happy official', 'Pharrell Williams - Happy'],
    ['Mark Ronson Uptown Funk official', 'Mark Ronson - Uptown Funk'],
    ['Camila Cabello Havana official', 'Camila Cabello - Havana'],
    ['Halsey Without Me official', 'Halsey - Without Me'],
    ['Travis Scott SICKO MODE official', 'Travis Scott - SICKO MODE'],
    ['Benson Boone Beautiful Things official', 'Benson Boone - Beautiful Things'],
    ['Sabrina Carpenter Espresso official', 'Sabrina Carpenter - Espresso'],
    ['Chappell Roan Good Luck Babe official', 'Chappell Roan - Good Luck, Babe!'],
    ['Teddy Swims Lose Control official', 'Teddy Swims - Lose Control'],
    ['Jack Harlow First Class official', 'Jack Harlow - First Class'],
    ['Elton John Sacrifice official', 'Elton John - Sacrifice'],
    ['Whitney Houston I Will Always Love You official', 'Whitney Houston - I Will Always Love You'],
    ['Queen Bohemian Rhapsody official', 'Queen - Bohemian Rhapsody'],
];
