export const UTAITE_SONGS = [
    ["Ado - Usseewa(うっせぇわ)", "Ado - Usseewa"],
    ["Ado - Odo(踊)", "Ado - Odo"],
    ["Ado - Gira Gira(ギラギラ)", "Ado - Gira Gira"],
    ["Ado - New Genesis(新時代)", "Ado - New Genesis"],
    ["Ado - I'm a Controversy(あたしは問題作)", "Ado - I'm a Controversy"],
    ["Ado - Tot Musica(トットムジカ)", "Ado - Tot Musica"],
    ["Ado - Kura Kura(クラクラ)", "Ado - Kura Kura"],
    ["Ado - Show(唱)", "Ado - Show"],
    ["Ado - Backlight(逆光)", "Ado - Backlight"],
    ["Ado - Fleeting Lullaby(ウタカタララバイ)", "Ado - Fleeting Lullaby"],
    ["yama - Haru wo Tsugeru(春を告げる)", "yama - Haru wo Tsugeru"],
    ["yama - Masshiro(真っ白)", "yama - Masshiro"],
    ["yama - a.m.3:21", "yama - a.m.3:21"],
    ["yama - Namae no Nai Kaibutsu(名前のない怪物) cover", "yama - Namae no Nai Kaibutsu"],
    ["yama - Oz.(オズ)", "yama - Oz."],
    ["yama - color", "yama - color"],
    ["yama - Shikisai(色彩)", "yama - Shikisai"],
    ["natori - Overdose(オーバードーズ)", "natori - Overdose"],
    ["natori - Friday Night(フライデー・ナイト)", "natori - Friday Night"],
    ["natori - Saru Shibai(猿芝居)", "natori - Saru Shibai"],
    ["natori - Sleepwalk(スリープウォーク)", "natori - Sleepwalk"],
    ["natori - Eureka(エウレカ)", "natori - Eureka"],
    ["Eve - Kaikai Kitan(廻廻奇譚)", "Eve - Kaikai Kitan"],
    ["Eve - Dramaturgy(ドラマツルギー)", "Eve - Dramaturgy"],
    ["Eve - As You Like It(お気に召すまま)", "Eve - As You Like It"],
    ["Eve - Nonsense Bungaku(ナンセンス文学)", "Eve - Nonsense Bungaku"],
    ["Eve - Tokyo Ghetto(トーキョーゲットー)", "Eve - Tokyo Ghetto"],
    ["Eve - Ao no Waltz(蒼のワルツ)", "Eve - Ao no Waltz"],
    ["Eve - Yoru wa Honoka(夜は仄か)", "Eve - Yoru wa Honoka"],
    ["Eve - Kororon(心海)", "Eve - Shinkai"],
    ["Eve - Fight Song(ファイトソング)", "Eve - Fight Song"],
    ["Eve - Bokura Mada Underground(僕らまだアンダーグラウンド)", "Eve - Bokura Mada Underground"],
    ["YOASOBI - Yoru ni Kakeru(夜に駆ける)", "YOASOBI - Yoru ni Kakeru"],
    ["YOASOBI - Idol(アイドル)", "YOASOBI - Idol"],
    ["YOASOBI - Kaibutsu(怪物)", "YOASOBI - Kaibutsu"],
    ["YOASOBI - Gunjo(群青)", "YOASOBI - Gunjo"],
    ["YOASOBI - Tabun(たぶん)", "YOASOBI - Tabun"],
    ["YOASOBI - Haruka(ハルカ)", "YOASOBI - Haruka"],
    ["YOASOBI - Shukufuku(祝福)", "YOASOBI - Shukufuku"],
    ["YOASOBI - Yuusha(勇者)", "YOASOBI - Yuusha"],
    ["YOASOBI - Biri-Biri", "YOASOBI - Biri-Biri"],
    ["Yorushika - Tada Kimi ni Hare(ただ君に晴れ)", "Yorushika - Tada Kimi ni Hare"],
    ["Yorushika - Dakara Boku wa Ongaku wo Yameta(だから僕は音楽を辞めた)", "Yorushika - Dakara Boku wa Ongaku wo Yameta"],
    ["Yorushika - Itte.(言って。)", "Yorushika - Itte."],
    ["Yorushika - Hana ni Borei(花に亡霊)", "Yorushika - Hana ni Borei"],
    ["Yorushika - Haru Dorobou(春泥棒)", "Yorushika - Haru Dorobou"],
    ["Yorushika - Elma(エルマ)", "Yorushika - Elma"],
    ["Yorushika - Matasaburou(又三郎)", "Yorushika - Matasaburou"],
    ["ZUTOMAYO - Byoushin wo Kamu(秒針を噛む)", "ZUTOMAYO - Byoushin wo Kamu"],
    ["ZUTOMAYO - Nouriue no Cracker(脳裏上のクラッカー)", "ZUTOMAYO - Nouriue no Cracker"],
    ["ZUTOMAYO - Humanoid(ヒューマノイド)", "ZUTOMAYO - Humanoid"],
    ["ZUTOMAYO - Obenkyou Shitoiteyo(お勉強しといてよ)", "ZUTOMAYO - Obenkyou Shitoiteyo"],
    ["ZUTOMAYO - Darken(暗く黒く)", "ZUTOMAYO - Darken"],
    ["ZUTOMAYO - Kira Killer(綺羅キラー)", "ZUTOMAYO - Kira Killer"],
    ["ZUTOMAYO - Time Left(残機)", "ZUTOMAYO - Time Left"],
    ["Vaundy - Kaiju no Hanauta(怪獣の花唄)", "Vaundy - Kaiju no Hanauta"],
    ["Vaundy - Odoriko(踊り子)", "Vaundy - Odoriko"],
    ["Vaundy - napori", "Vaundy - napori"],
    ["Vaundy - Tokyo Flash(東京フラッシュ)", "Vaundy - Tokyo Flash"],
    ["Vaundy - Fukakouryoku(不可幸力)", "Vaundy - Fukakouryoku"],
    ["Vaundy - Hadaka no Yuusha(裸の勇者)", "Vaundy - Hadaka no Yuusha"],
    ["Vaundy - Chainsaw Blood", "Vaundy - Chainsaw Blood"],
    ["Kenshi Yonezu - Lemon", "Kenshi Yonezu - Lemon"],
    ["Kenshi Yonezu - Kick Back", "Kenshi Yonezu - Kick Back"],
    ["Kenshi Yonezu - Loser", "Kenshi Yonezu - Loser"],
    ["Kenshi Yonezu - Peace Sign(ピースサイン)", "Kenshi Yonezu - Peace Sign"],
    ["Kenshi Yonezu - Eine Kleine(アイネクライネ)", "Kenshi Yonezu - Eine Kleine"],
    ["Kenshi Yonezu - Flamingo", "Kenshi Yonezu - Flamingo"],
    ["Kenshi Yonezu - M87(M八七)", "Kenshi Yonezu - M87"],
    ["Kenshi Yonezu - Lady", "Kenshi Yonezu - Lady"],
    ["Kenshi Yonezu - Chikyuugi(地球儀)", "Kenshi Yonezu - Chikyuugi"],
    ["imase - NIGHT DANCER", "imase - NIGHT DANCER"],
    ["imase - Have a good day", "imase - Have a good day"],
    ["imase - Nagisa", "imase - Nagisa"],
    ["imase - Heroine(ヒロイン)", "imase - Heroine"],
    ["Fuji Kaze - Shinunoga E-Wa(死ぬのがいいわ)", "Fuji Kaze - Shinunoga E-Wa"],
    ["Fuji Kaze - Matsuri(まつり)", "Fuji Kaze - Matsuri"],
    ["Fuji Kaze - Kirari(きらり)", "Fuji Kaze - Kirari"],
    ["Fuji Kaze - Grace", "Fuji Kaze - Grace"],
    ["Fuji Kaze - Michi Teyu Ku (Overflowing)(満ちてゆく)", "Fuji Kaze - Michi Teyu Ku"],
    ["Yuuri - Dry Flower(ドライフラワー)", "Yuuri - Dry Flower"],
    ["Yuuri - Betelgeuse(ベテルギウス)", "Yuuri - Betelgeuse"],
    ["Yuuri - Peter Pan(ピーターパン)", "Yuuri - Peter Pan"],
    ["Yuuri - Kakurenbo(かくれんぼ)", "Yuuri - Kakurenbo"],
    ["Yuuri - Leo(レオ)", "Yuuri - Leo"],
    ["Aimer - Zankyou Sanka(残響散歌)", "Aimer - Zankyou Sanka"],
    ["Aimer - Kataomoi(カタオモイ)", "Aimer - Kataomoi"],
    ["Aimer - Ref:rain", "Aimer - Ref:rain"],
    ["Aimer - Brave Shine", "Aimer - Brave Shine"],
    ["Aimer - I beg you", "Aimer - I beg you"],
    ["Aimer - Spark-Again", "Aimer - Spark-Again"],
    ["Eill - Koko de Iki wo Shite(ここで息をして)", "Eill - Koko de Iki wo Shite"],
    ["Eill - Fake Love", "Eill - Fake Love"],
    ["Kanaria - King", "Kanaria - King"],
    ["Kanaria - Envy Baby(エンヴィーベイビー)", "Kanaria - Envy Baby"],
    ["Kanaria - Yoidore Shirazu(酔いどれ知らず)", "Kanaria - Yoidore Shirazu"],
    ["Kanaria - Requiem(レクイエム)", "Kanaria - Requiem"]
];
